---
abstract: "Pure Perl implementation of 'HikiDoc' which is a text-to-HTML conversion tool."
author:
  - "The original 'HikiDoc' was written by Kazuhiko <kazuhiko@fdiary.net>"
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-HikiDoc
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Text::HikiDoc:
    file: lib/Text/HikiDoc.pm
    version: 1.020
  Text::HikiDoc::Plugin:
    file: lib/Text/HikiDoc/Plugin.pm
  Text::HikiDoc::Plugin::aa:
    file: lib/Text/HikiDoc/Plugin/aa.pm
  Text::HikiDoc::Plugin::br:
    file: lib/Text/HikiDoc/Plugin/br.pm
  Text::HikiDoc::Plugin::e:
    file: lib/Text/HikiDoc/Plugin/e.pm
  Text::HikiDoc::Plugin::ins:
    file: lib/Text/HikiDoc/Plugin/ins.pm
  Text::HikiDoc::Plugin::sub:
    file: lib/Text/HikiDoc/Plugin/sub.pm
  Text::HikiDoc::Plugin::sup:
    file: lib/Text/HikiDoc/Plugin/sup.pm
  Text::HikiDoc::Plugin::syntaxhighlighter:
    file: lib/Text/HikiDoc/Plugin/syntaxhighlighter.pm
  Text::HikiDoc::Plugin::texthighlight:
    file: lib/Text/HikiDoc/Plugin/texthighlight.pm
  Text::HikiDoc::Plugin::vimcolor:
    file: lib/Text/HikiDoc/Plugin/vimcolor.pm
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/higemaru/p5-text-hikidoc/issues
  homepage: https://github.com/higemaru/p5-text-hikidoc
  repository: git://github.com/higemaru/p5-text-hikidoc.git
version: 1.020
x_contributors:
  - 'KAWABATA Kazumichi <kawabata@cpan.org>'
